SET IDENTITY_INSERT [dbo].[LibroSet] ON
INSERT INTO [dbo].[LibroSet] ([idLibro], [tituloLibro], [categoriaLibro], [editorialLibro], [ISBN], [precioLibro], [descripcionLibro], [Autor_idAutor]) VALUES (1, N'Huasipungo', N'	Novela indigenista', N'Litec', N'132-13246587', CAST(8 AS Decimal(18, 0)), N'Huasipungo es una novela del escritor ecuatoriano Jorge Icaza Coronel. La historia transcurre en Ecuador en la primera mitad del siglo 20, siendo sus personajes principales los indios de los huasipungos, huasipungos son los ranchos, propiedad de los patrones, en los que habitan estas personas. Es una de las obras más representativas de la literatura indigenista, movimiento que precedió al realismo mágico y que enfatizaba un realismo brutal.', 1)
INSERT INTO [dbo].[LibroSet] ([idLibro], [tituloLibro], [categoriaLibro], [editorialLibro], [ISBN], [precioLibro], [descripcionLibro], [Autor_idAutor]) VALUES (3, N'Cumandá', N'Romanticismo', N'Litec', N'132-65465998', CAST(9 AS Decimal(18, 0)), N'Cumandá o Un drama entre salvajes es una novela escrita por el ensayista, novelista, político, y pintor ecuatoriano Juan León Mera. Fue enviada al Excmo. Señor Director de la Real Academia Española el 10 de marzo de 1877 desde la ciudad de Ambato, Ecuador con el objetivo de que ésta sea presentada a la Real Academia. La novela tiene lugar en el Oriente ecuatoriano a mediados del siglo XVIII.', 2)
INSERT INTO [dbo].[LibroSet] ([idLibro], [tituloLibro], [categoriaLibro], [editorialLibro], [ISBN], [precioLibro], [descripcionLibro], [Autor_idAutor]) VALUES (4, N'A la costa', N'Realismo', N'Litec', N'365-46549849', CAST(10 AS Decimal(18, 0)), N'A la costa es una novela histórica escrita por el ecuatoriano Luis Alfredo Martínez y publicada originalmente en 1904,1​ considerada la obra cumbre del autor. La trama se desarrolla a finales del siglo XIX en medio de los cambios políticos y sociales provocados por la Revolución liberal de Ecuador.', 3)
INSERT INTO [dbo].[LibroSet] ([idLibro], [tituloLibro], [categoriaLibro], [editorialLibro], [ISBN], [precioLibro], [descripcionLibro], [Autor_idAutor]) VALUES (5, N'Entre Marx y una mujer desnuda', N'Realismo Mágico', N'LItec', N'357-4954984', CAST(12 AS Decimal(18, 0)), N'La película cuenta la historia de Galo Gálvez durante la década de los sesenta en la ciudad de Quito. Un intelectual que lucha entre la marginación del Partido Comunista y la mala convivencia con su compañera de partido Margamaría, quien ha sido su novia desde la niñez.

Basada en la novela de Adoum, en el film el Autor se vuelve un personaje, narrando lo que viven sus amigos y sus propias fantasías, así la película se vuelve entre real e imaginaria.', 4)
INSERT INTO [dbo].[LibroSet] ([idLibro], [tituloLibro], [categoriaLibro], [editorialLibro], [ISBN], [precioLibro], [descripcionLibro], [Autor_idAutor]) VALUES (9, N'El Chulla Romero y Flores', N'Novela', N'Litec', N'354/7984561', CAST(9 AS Decimal(18, 0)), N'El Chulla Romero y Flores (Quito, 1958), es una novela del escritor ecuatoriano Jorge Icaza. Es una de las obras más traducidas de este autor, y figura entre las más importantes de su obra.', 1)
INSERT INTO [dbo].[LibroSet] ([idLibro], [tituloLibro], [categoriaLibro], [editorialLibro], [ISBN], [precioLibro], [descripcionLibro], [Autor_idAutor]) VALUES (10, N'Las cruces sobre el agua', N'Novela', N'Litec', N'354-6549849', CAST(10 AS Decimal(18, 0)), N'Las cruces sobre el agua es una novela publicada en el año 1946 y escrita por Joaquín Gallegos Lara, que lo situó entre los iniciadores del tema urbano en la narrativa ecuatoriana. La culminación y detonante argumental, es la masacre del 15 de noviembre de 1922.

La novela corresponde a una época avanzada del realismo socialista ecuatoriano, ya menos costumbrista y desplazado su escenario hacía las ciudades, donde el autor ubica a los protagonistas en los sectores más humildes y marginados. Por su contenido histórico y sociológico es una obra clásica de la literatura ecuatoriana.', 5)
SET IDENTITY_INSERT [dbo].[LibroSet] OFF
